### ISSUE TITLE
how to import the ReactWebComponent?

### ISSUE THREAD

**Issue by conor909** [LukasBombach/react-web-component#2]
In the basic usage example you define a file:

```
import React from 'react';
import ReactWebComponent from 'react-web-component';
 
class App extends React.Component {
  render() {
    return <div>Hello World!</div>;
  }
}
 
ReactWebComponent.create(<App />, 'my-component');
```

But how do I import it into my html file?  I tried `<link rel="import" href="../path/to/file.js">`, and also adding `export default ReactWebComponent.create(<App />, 'my-component');` to the js file.  But nothing is working.  Could you explain this in the docs for people new to Web Components?

**Comment by mnemanja** [comment]
Is the `html` file in question a part of the react project? Like the `public/index.html`? 

If not, then you'd need to host the `ReactWebComponent` with `CORS` enabled, and then do something like `<link rel="import" href="http://localhost:1337">`.

I'm not using this library at the moment but I have a similar setup.
Hope this helps.

**Comment by mnemanja** [comment]
I've tried it right now in conjunction with create-react-app and it does not work.

**Comment by mnemanja** [comment]
Instead of using the `http import` (<link rel..) try importing it directly into your javascript file, e.g.
![image](https://user-images.githubusercontent.com/1423218/36379509-30774594-157f-11e8-9581-0cb3588ae02e.png)

I'm using React and I've managed to make it work by either serving it from the outside and using the `http import`, or hosting it locally and importing it like this:
![image](https://user-images.githubusercontent.com/1423218/36379546-524977b4-157f-11e8-9de6-a1a89dd1bb66.png)

**Comment by mnemanja** [comment]
@conor909 
In my case I'm using the `create-react-app` and there I've replaced the `index.js` content with the new code, like the one you've mentioned.
When I start the development I see an empty page, but when I put the web component `<footer-component />` in the 
/public/index.html file (instead of `<div id="root"></div>`) I can see it locally in the development environment.

Maybe this will help you :) 
Let me know how it goes?

**Comment by conor909** [comment]
Sorry for the late reply, I had to park this project for a while. I wasn't familiar with just calling the file with no variable and expecting the component to be available. But since playing with web components more I understand how they are used and imported.  Thanks for the responses.

**Comment by Stevemoretz** [comment]
And if you explained we could understand how they are used and imported too.that's why the issues are public.

**Comment by conor909** [comment]
@Stevemoretz 
It's not an issue to do with this library - you just need to read up a bit on how WebComponents work
